### ISSUE TITLE
Using as middleware and getting auto start warning

### ISSUE THREAD

**Issue by JamiesonRoberts** [JoshWillik/ghost-as-middleware#1]
First off, this is exactly what I needed, so thank you for getting it working.

I am having a bit of of a problem with mine. When I start things up I'm getting the following message

 Warning: Ghost no longer starts automatically when using it as an npm module. 
 If you're seeing this message, you may need to update your custom code. 
 Please see the docs at http://tinyurl.com/npm-upgrade for more information.

The source code for how I'm using it can be found here.
https://github.com/JamiesonRoberts/Jamieson-Roberts-Website/tree/feature-ghost-setup

Anything stick out as to what might be causing the error?

**Comment by JoshWillik** [comment]
Way back when, Ghost was even less friendly to being used as middleware.
When you started it up, it was just `ghost()` and you couldn't really do much to control it.

When the ghost API was changed to a promise based setup that returned an express server, there needed to be a message to people who the people who ran `ghost()` and expected things to work.

However, this middleware never calls `ghost.listen()`, so the message pops up.
This is completely harmless, feel free to ignore it.

The history of this issue can be found over at TryGhost/ghost#3789

**Comment by JamiesonRoberts** [comment]
Ah ok, perfect, thank you for the explanation!
